
function(create_qwk_binding)
    set(options)
    set(one_value_args TARGET ORIGIN_LIB HEADER TYPESYSTEM INSTALL_DIR)
    set(multi_value_args SOURCES EXTRA_INCLUDES QT_MODULES)
    cmake_parse_arguments(ARG "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    # Common Shiboken Options
    # set(SHIBOKEN_OPTIONS 
    #     "-I${CMAKE_CURRENT_SOURCE_DIR}/install/include"
    #     "-I${CMAKE_CURRENT_SOURCE_DIR}/install/include/QWindowKit"
    # )
    
    # Add extra includes if provided
    if(ARG_EXTRA_INCLUDES)
        list(APPEND SHIBOKEN_OPTIONS ${ARG_EXTRA_INCLUDES})
    endif()

    shiboken_generator_create_binding(
        EXTENSION_TARGET ${ARG_TARGET}
        GENERATED_SOURCES ${ARG_SOURCES}
        HEADERS ${ARG_HEADER}
        TYPESYSTEM_FILE ${ARG_TYPESYSTEM}
        LIBRARY_TARGET ${ARG_ORIGIN_LIB}
        FORCE_LIMITED_API
        QT_MODULES ${ARG_QT_MODULES}
        SHIBOKEN_EXTRA_OPTIONS ${SHIBOKEN_OPTIONS}
    )

    target_sources(${ARG_TARGET} PRIVATE ${ARG_SOURCES})
    
    # Install the module (.pyd)
    install(TARGETS ${ARG_TARGET} DESTINATION ${ARG_INSTALL_DIR})
    
    # Install the .pyi stub (generated by shiboken6 if configured, or we assume it exists)
    # Note: shiboken_generator_create_binding doesn't automatically add --generate-pyi in all versions/wrappers
    # We assume the user might have patched shiboken or we rely on post-process.
    # However, based on previous context, we removed --generate-pyi because it wasn't supported by the macro.
    # So we don't install .pyi here. The post-install script generates them.
    # BUT, if we want to support it if available, we can keep it simple.
    # For now, let's match the user's snippet structure which installs the target.
    
endfunction()
